### ISSUE TITLE
'Vinelab\Tracing\Contracts\Tracer' is not Instantiable

### ISSUE THREAD

**Issue by KinaneD** [Vinelab/tracing-laravel#28] opened 2020-11-24 16:39 UTC
Running on:
- Laravel 8.15
- PHP v7.4
- Phpunit v9.4.3

We are adding a Phpunit functionality to provide some test coverage html page running the following command:
`./vendor/bin/phpunit --coverage-html html`

We get the following error:
![Screenshot 2020-11-24 at 17 51 46](https://user-images.githubusercontent.com/12595235/100123682-75fc6200-2e83-11eb-83e2-50c9b029fe39.png)

> It is worth mentioning that we have in the same project a number of RabbitMq consumers running with Tracing enabled with no issues. And running the phpunit test suit goes as expected.

Once thing to mention is that to suppress Tracing while runing phpunit test we add the following to the `phpunit.xml` file:
`<server name="TRACING_DRIVER" value="'null'"/>`

Could this issue be pointing to a particular caveat within the service provider? 

**_Update_**
Removing the `null` Tracing driver from `phpunit.xml` apparently circumvent the above issue.

**Comment by adiachenko** [comment] 2020-11-27 23:15
I wager that this and #29 are somehow related since they are effectively tied to the same lines in TracingServiceProvider and in both cases the issue seem to be triggered by certain changes in config. Maybe check the register method on it:

<img width="918" alt="image" src="https://user-images.githubusercontent.com/10194667/100488464-13bb8f80-3117-11eb-9316-28a02e28cafc.png">

P.S. Unlike with #29 I didn't have the chance to test this scenario yet. I'll reach out to you later if I discover something of value.

**Comment by IlliaBalia** [comment] 2021-01-04 18:05
@KinaneD @adiachenko I was not able to replicate the error, to my great surprise.
Apparently, the issue is/was related to whatever else but the package itself.

Feel free to close the issue.

**Closed** 2021-01-04 18:59 UTC
Labels: bug
